/*
 * Copyright (C) 2019 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_here_android_olp_TesterActivity */

#ifndef _Included_com_here_android_olp_TesterActivity
#define _Included_com_here_android_olp_TesterActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_here_android_olp_TesterActivity
 * Method:    runTests
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_here_android_olp_TesterActivity_runTests
  (JNIEnv *, jobject, jstring, jobjectArray);

JNIEXPORT void JNICALL
JJava_com_here_android_olp_TesterActivity_setUpNative(JNIEnv* /*env*/, jobject /*obj*/,
                                                       jobject context);

JNIEXPORT void JNICALL
Java_com_here_android_olp_TesterActivity_tearDownNative(JNIEnv* /*env*/, jobject /*obj*/);

JNIEXPORT jint JNICALL
JNI_OnLoad(JavaVM* vm, void* /*reserved*/);

#ifdef __cplusplus
}
#endif
#endif
