---
excludes:
  paths:
    - pattern: ".*build\\.gradle"
      reason: "TEST_TOOL_OF"
      comment: "This project contains tests which are not distributed"
    - pattern: "cmake/**"
      reason: "BUILD_TOOL_OF"
      comment: "The files are only used for building the code. Not included in released artifacts."
    - pattern: "docs/**"
      reason: "DOCUMENTATION_OF"
      comment: "The files are only used for documentation. Not included in released artifacts."
    - pattern: "examples/**"
      reason: "EXAMPLE_OF"
      comment: "Directory is only used for examples. Not included in released artifacts."
    - pattern: "tests/**"
      reason: "TEST_OF"
      comment: "Directory is only used for testing. Not included in released artifacts."
