---
excludes:
  paths:
    - pattern: ".*build\\.gradle"
      reason: "TEST_TOOL_OF"
      comment: "This project contains tests which are not distributed"
    - pattern: "tests/utils/mock-server/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "The project is not distributed for Node.js."
