language: cpp
matrix:
  include:
  - os: linux
    env:
    - WORKSPACE=$TRAVIS_BUILD_DIR
    dist: xenial
    addons:
      apt:
        packages:
        - cmake 
        - libssl-dev 
        - libcurl4-openssl-dev 
        - libboost-all-dev 
    script:
    - $WORKSPACE/scripts/linux_build.sh
  - os: windows
    env: 
    - BUILD_TYPE=RelWithDebInfo WORKSPACE=$TRAVIS_BUILD_DIR
    install: 
    - choco install openssl.light
    script:
    - $WORKSPACE/scripts/windows_build.sh
branches:
  only:
  - master	
