language: cpp
os: linux
dist: xenial
env: WORKSPACE=$TRAVIS_BUILD_DIR
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libcurl4-openssl-dev 
    - libboost-all-dev
    - clang
matrix:
  include:
  - compiler: clang
    env: BUILD_TYPE=RelWithDebInfo WORKSPACE=$TRAVIS_BUILD_DIR
    name: Linux Build using clang 
    script: $WORKSPACE/scripts/linux/build.sh
  - compiler: gcc
    env: BUILD_TYPE=COVERAGE WORKSPACE=$TRAVIS_BUILD_DIR
    name: Linux Build using gcc & tests & code coverage
    script: $WORKSPACE/scripts/linux/build.sh && $WORKSPACE/scripts/linux/test.sh
  - language: android
    name: Android Build
    os : linux
    dist: xenial
    language: cpp
    before_script:
    - wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
    - wget https://dl.google.com/android/repository/android-28_r06.zip
    - unzip -qq android-ndk-r20-linux-x86_64.zip
    - unzip -qq android-28_r06.zip
    - export ANDROID_SDK_ROOT="$TRAVIS_BUILD_DIR/android-9.0"
    - export ANDROID_NDK_HOME="$TRAVIS_BUILD_DIR/android-ndk-r20"
    script: $WORKSPACE/scripts/android/build.sh
  - os: osx
    env: BUILD_TYPE=RelWithDebInfo WORKSPACE=$TRAVIS_BUILD_DIR
    name: OSX Build
    script: $WORKSPACE/scripts/linux/build.sh
  - os: osx
    name: IOS Build
    script: $WORKSPACE/scripts/ios/build.sh  
branches:
  only:
  - master
