language: cpp
os: linux
dist: xenial
env:
  global:
  - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  - WORKSPACE=$TRAVIS_BUILD_DIR
addons:
  apt:
    packages:
    - libboost-all-dev
    - libssl-dev
    - libcurl4-openssl-dev 
    - clang
matrix:
  include:
  - compiler: clang
    env: BUILD_TYPE=RelWithDebInfo WORKSPACE=$TRAVIS_BUILD_DIR
    name: Linux Build using clang 
    script: $WORKSPACE/scripts/linux/psv/travis_build_psv.sh
  - compiler: gcc
    env: BUILD_TYPE=COVERAGE WORKSPACE=$TRAVIS_BUILD_DIR
    name: Linux Build using gcc & tests & code coverage
    script: $WORKSPACE/scripts/linux/psv/travis_build_psv.sh && $WORKSPACE/scripts/linux/psv/travis_test_psv.sh
  - language: android
    dist: xenial
    jdk: oraclejdk8
    name: Android Build
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28      
      - extra-google-m2repository
      - extra-android-m2repository # for design library
      licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+    
      - patcher
      - ndk-bundle
    before_install:
    - echo y | sdkmanager "ndk-bundle"    
    before_script:
    - wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
    - unzip -qq android-ndk-r20-linux-x86_64.zip
    script: $WORKSPACE/scripts/android/build.sh
  - os: osx
    osx_image: xcode10.2
    env: BUILD_TYPE=RelWithDebInfo WORKSPACE=$TRAVIS_BUILD_DIR
    name: OSX Build
    script: $WORKSPACE/scripts/linux/psv/travis_build_psv.sh
  - os: osx
    osx_image: xcode10.2
    name: IOS Build
    script: $WORKSPACE/scripts/ios/build.sh  
branches:
  only:
  - master
