language: cpp
matrix:
  include:
  - os: linux
    services: docker
    script:
    - echo SERVICE_ID=${SERVICE_ID} >>env_file && echo SERVICE_SECRET=${SERVICE_SECRET} >>env_file
    - docker run --rm --privileged -v ${TRAVIS_BUILD_DIR}:/mnt/test --env-file=env_file grebec/olp-test /bin/bash -x /mnt/test/script_build.sh
  - os: windows
    env: BUILD_TYPE=Release
    install: 
    - choco install openssl.light
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBoost_LIBRARY_DIR_DEBUG="$TRAVIS_BUILD_DIR/build/external/boost/build/$BUILD_TYPE" -DBoost_ARCHITECTURE=x64
    script:
      - cmake --build . --config $BUILD_TYPE
      - mkdir $TRAVIS_BUILD_DIR/test_results
    #Authentication Test
      - echo ">>> Authentication Test ... >>>"
      - cd $TRAVIS_BUILD_DIR/build/olp-cpp-sdk-authentication/test/unit/$BUILD_TYPE
      - "./olp-authentication-test.exe --gtest_output=xml 
                                      --service_id=$SERVICE_ID
                                      --service_secret=$SERVICE_SECRET
                                      --production_service_id=$PRODUCTION_SERVICE_ID
                                      --production_service_secret=$PRODUCTION_SERVICE_SECRET
                                      --facebook_access_token=$FACEBOOK_ACCESS_TOKEN
                                      --facebook_app_id=$FACEBOOK_APP_ID
                                      --google_client_id=$GOOGLE_CLIENT_ID
                                      --google_client_secret=$GOOGLE_CLIENT_SECRET
                                      --google_client_token=$GOOGLE_CLIENT_TOKEN
                                      --arcgis_app_id=$ARCGIS_APP_ID
                                      --arcgis_access_token=$ARCGIS_ACCESS_TOKEN
                                      --integration_production_service_id=$INTEGRATION_PRODUCTION_SERVICE_ID
                                      --integration_production_service_secret=$INTEGRATION_PRODUCTION_SERVICE_SECRET
      || echo 'Authentication Test failed'"
      - "[ -f 'test_detail.xml' ] && cp test_detail.xml $TRAVIS_BUILD_DIR/test_results/olp-authentication-test.xml"
    #Core - Cache Test
      - echo ">>> Core - Cache Test ... >>>"
      - cd $TRAVIS_BUILD_DIR/build/olp-cpp-sdk-core/tests/cache/$BUILD_TYPE
      - "./cache-test.exe --gtest_output=xml || echo 'Core - Cache Test failed'"
      - "[ -f 'test_detail.xml' ] && cp test_detail.xml $TRAVIS_BUILD_DIR/test_results/cache-test.xml"
    #Core - Geo Test
      - echo ">>> Core - Geo Test ... >>>"
      - cd $TRAVIS_BUILD_DIR/build/olp-cpp-sdk-core/tests/geo/$BUILD_TYPE
      - "./geo-test.exe --gtest_output=xml || echo 'Core - Geo Test failed'"
      - "[ -f 'test_detail.xml' ] && cp test_detail.xml $TRAVIS_BUILD_DIR/test_results/geo-test.xml"
    #Core - Network Test
      - echo ">>> Core - Network Test ... >>>"
      - cd $TRAVIS_BUILD_DIR/build/olp-cpp-sdk-core/tests/network/$BUILD_TYPE
      - "./olp-core-network-test.exe --gtest_output=xml || echo 'Core - Network Test failed'"
      - "[ -f 'test_detail.xml' ] && cp test_detail.xml $TRAVIS_BUILD_DIR/test_results/olp-core-network-test.xml"
    #Core - Client Test
      - echo ">>> Core - Client Test ... >>>"
      - cd $TRAVIS_BUILD_DIR/build/olp-cpp-sdk-core/tests/olpclient/$BUILD_TYPE
      - "./olpclient-test.exe --gtest_output=xml --endpoint='https://account.api.here.com/oauth2/token'
                             --catalog='hrn:here:data:::hereos-internal-test-v2'
      || echo 'Core - Client Test failed'"
      - "[ -f 'test_detail.xml' ] && cp test_detail.xml $TRAVIS_BUILD_DIR/test_results/olpclient-test.xml"
    #Data Service Read Test
      - echo ">>> Data Service Read Test ... >>>"
      - cd $TRAVIS_BUILD_DIR/build/olp-cpp-sdk-dataservice-read/test/unit/$BUILD_TYPE
      - "./olp-dataservice-read-test.exe --gtest_output=xml --endpoint='https://account.api.here.com/oauth2/token' 
                                        --catalog='hrn:here:data:::hereos-internal-test-v2' 
                                        --appid=$DATASERVICE_READ_APPID 
                                        --secret=$DATASERVICE_READ_SECRET
      || echo 'Data Service Read Test failed'"
      - "[ -f 'test_detail.xml' ] && cp test_detail.xml $TRAVIS_BUILD_DIR/test_results/olp-dataservice-read-test.xml"
    #Data Service Write Test
      - echo ">>> Data Service Write Test ... >>>"
      - cd $TRAVIS_BUILD_DIR/build/olp-cpp-sdk-dataservice-write/test/$BUILD_TYPE
      - "./olp-dataservice-write-test.exe --gtest_output=xml
                                         --endpoint=https://account.api.here.com/oauth2/token
                                         --catalog=hrn:here:data:::olp-cpp-sdk-ingestion-test-catalog
                                         --layer=olp-cpp-sdk-ingestion-test-stream-layer
                                         --layer2=olp-cpp-sdk-ingestion-test-stream-layer-2
                                         --layer-sdii=olp-cpp-sdk-ingestion-test-stream-layer-sdii
                                         --versioned-layer=olp-cpp-sdk-ingestion-test-versioned-layer
                                         --volatile-layer=olp-cpp-sdk-ingestion-test-volatile-layer
                                         --index-layer=olp-cpp-sdk-ingestion-test-index-layer
                                         --appid=$DATASERVICE_WRITE_APPID
                                         --secret=$DATASERVICE_WRITE_SECRET
      || echo 'Data Service Write Test failed'"
      - "[ -f 'test_detail.xml' ] && cp test_detail.xml $TRAVIS_BUILD_DIR/test_results/olp-dataservice-write-test.xml"
      - echo "tests finished"
