coverage:
  range: 60..100
  round: nearest
  precision: 1
  status:
    project:
      core:
        paths:
          - olp-cpp-sdk-core
        threshold: 1
      authentication:
        paths:
          - olp-cpp-sdk-authentication
        threshold: 1
      dataservice-read:
        paths:
          - olp-cpp-sdk-dataservice-read
        threshold: 1
      dataservice-write:
        paths:
          - olp-cpp-sdk-dataservice-write
        threshold: 1
ignore:
  - olp-cpp-sdk-authentication/tests
  - olp-cpp-sdk-core/src/http/android
  - olp-cpp-sdk-core/src/http/curl
  - olp-cpp-sdk-core/src/http/ios
  - olp-cpp-sdk-core/src/http/winhttp
  - olp-cpp-sdk-core/src/http/Network.cpp
  - olp-cpp-sdk-core/tests
  - olp-cpp-sdk-dataservice-read/tests
  - olp-cpp-sdk-dataservice-write/tests
  - olp-cpp-sdk-dataservice-write/src/AutoFlushController.cpp
  - olp-cpp-sdk-dataservice-write/src/AutoFlushController.h
  - olp-cpp-sdk-dataservice-write/src/AutoFlushSettings.h
  - olp-cpp-sdk-dataservice-write/src/BackgroundTaskCollection.cpp
  - olp-cpp-sdk-dataservice-write/src/BackgroundTaskCollection.h
  - olp-cpp-sdk-dataservice-write/src/DefaultFlushEventListener.cpp
  - olp-cpp-sdk-dataservice-write/src/DefaultFlushEventListener.h
  - olp-cpp-sdk-dataservice-write/src/FlushEventListener.h
  - olp-cpp-sdk-dataservice-write/src/FlushMetrics.h
  - tests
  - scripts
  - examples
  - docs
  - external
  - build

