@startuml

skinparam componentStyle uml2

[authentication] --> [core] :  uses
[dataservice-read] --> [core] : uses
[dataservice-write] --> [core] : uses

cloud "HERE Cloud" {
  [AAA]
  note bottom of AAA : offers HERE Authentication and\n Authorization API
  [HERE platform]
  note bottom of HERE platform : offers Data API
}
[core] --> [AAA]
[core] --> [HERE platform]

@enduml
