name: FV_Pipelines

on:
  push:
    branches:
      - master

jobs:
  fv-build-ios-network-test:
    name: FV / iOS clang / Network tests
    runs-on: macos-latest
    env:
      BUILD_TYPE: RelWithDebInfo
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build with tests
        run: ./scripts/ios/fv/gh-actions-build-with-tests-fv.sh
        shell: bash
      - name: Test iOS FV Network
        run: ./scripts/ios/fv/gh-actions-functional-network-test.sh
        shell: bash

  fv-android-emulator-build-test:
    name: FV.Android.Emulator.Build.Test.API21.ABIx86_64.NDK-22.
    runs-on: ubuntu-latest
    env:
      SEGFAULT_SIGNALS: all
      BUILD_TYPE: RelWithDebInfo
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Verification of cmake script
      run: ls -la ${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake  &&  ls -la ${ANDROID_NDK_HOME}/prebuilt &&  ls -la ${ANDROID_NDK_HOME}/ndk-build
    - name: Android Emulator Test
      run: scripts/android/build-test-emulator.sh
      shell: bash
