name: FV_Pipelines

on:
    schedule:
    # temporary run job only once a month.
    - cron: '* 5 1 * *'

env:
  LD_PRELOAD: /lib/x86_64-linux-gnu/libSegFault.so
  SEGFAULT_SIGNALS: all

jobs:
  fv-build-ios-network-test:
    name: FV / iOS clang / Network tests
    runs-on: macos-10.15
    env:
      BUILD_TYPE: RelWithDebInfo
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build with tests
        run: ./scripts/ios/fv/gh-actions-build-with-tests-fv.sh
        shell: bash
      - name: Test FV Network
        run: ./scripts/ios/fv/gh-actions-functional-network-test.sh
        shell: bash

  fv-android-amulator-build-test:
    name: MV.Android.Emulator.Build.Test.API21.ABIx86_64.NDK-Latest.
    runs-on: ubuntu-20.04
    env:
      ANDROID_NDK_HOME: $(ANDROID_HOME)/ndk-bundle
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Verification of cmake script
      run: ls -la $(ANDROID_NDK_HOME)/build/cmake/android.toolchain.cmake
      shell: bash
    - name: Android Emulator Test
      run: ANDROID_NDK_HOME=$(ANDROID_NDK_HOME) && scripts/android/build-test-emulator.sh
      shell: bash